### ISSUE TITLE
Build broken

### ISSUE THREAD

**Issue by inducer** [conda-forge/pudb-feedstock#8]
So while #7 passed as a PR, it died when actually doing the build. I figured I'd rerender (it looked like some type of conda-internal thing broke). But with this set of versions:

```
conda                     4.3.23                   py36_0    conda-forge
conda-build               2.1.17                   py36_0    conda-forge
conda-build-all           1.1.0                    py36_0    conda-forge
conda-env                 2.6.0                         0    conda-forge
conda-smithy              2.3.3                    py36_0    conda-forge
conda-verify              2.0.0                    py36_0    conda-forge
```

I get this backtrace on trying to rerender:

```
$ conda smithy rerender
Traceback (most recent call last):
  File "/home/andreas/pack/miniconda3/bin/conda-smithy", line 4, in <module>
    import conda_smithy.cli
  File "/home/andreas/pack/miniconda3/lib/python3.6/site-packages/conda_smithy/cli.py", line 14, in <module>
    from . import ci_register
  File "/home/andreas/pack/miniconda3/lib/python3.6/site-packages/conda_smithy/ci_register.py", line 10, in <module>
    from . import github
  File "/home/andreas/pack/miniconda3/lib/python3.6/site-packages/conda_smithy/github.py", line 16, in <module>
    from . import configure_feedstock
  File "/home/andreas/pack/miniconda3/lib/python3.6/site-packages/conda_smithy/configure_feedstock.py", line 48, in <module>
    from conda_build_all.version_matrix import special_case_version_matrix, filter_cases
  File "/home/andreas/pack/miniconda3/lib/python3.6/site-packages/conda_build_all/version_matrix.py", line 19, in <module>
    for attr in ['Unsatisfiable', 'NoPackagesFound'])
  File "/home/andreas/pack/miniconda3/lib/python3.6/site-packages/conda_build_all/version_matrix.py", line 19, in <genexpr>
    for attr in ['Unsatisfiable', 'NoPackagesFound'])
AttributeError: module 'conda.resolve' has no attribute 'NoPackagesFound'
```

@asmeurer any ideas?

**Comment by inducer** [comment]
Broken build for reference: https://circleci.com/gh/conda-forge/pudb-feedstock/18

**Comment by asmeurer** [comment]
@conda-forge/core

**Comment by mwcraig** [comment]
You need to pin conda at 4.3.22. It is conceivable that 4.3.24 will work, but 4.3.23 defintiely will not.

**Comment by inducer** [comment]
> You need to pin conda at 4.3.22. It is conceivable that 4.3.24 will work, but 4.3.23 defintiely will not.

Thanks!

**Comment by asmeurer** [comment]
It's still broken.

**Comment by inducer** [comment]
Is this something that's wrong on the Anaconda side, or does the package need to be fixed?

**Comment by asmeurer** [comment]
This is the error

```
$ upload_or_check_non_existence ./recipe conda-forge --channel=main
Using Anaconda API: https://api.anaconda.org
Using Anaconda API: https://api.anaconda.org
[ERROR] 
Traceback (most recent call last):
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/binstar_client/commands/upload.py", line 133, in add_release
    aserver_api.release(username, package_name, version)
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/binstar_client/__init__.py", line 377, in release
    self._check_response(res)
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/binstar_client/__init__.py", line 216, in _check_response
    raise ErrCls(msg, res.status_code)
binstar_client.errors.NotFound: ("release version=u'2017.1.3' does not exist", 404)
```

Something that seems off to me, but maybe it's unrelated, why does the error message use a `u` string when the code is all Python 3?

**Comment by asmeurer** [comment]
If it's an issue with Anaconda (client or .org), I would expect to see it in other feedstocks too. None of the most recently updated feedstocks have errors (scroll down at https://github.com/conda-forge), but pudb is also at this point in time the most recently updated feedstock, so maybe we are the first to see it.

**Comment by jakirkham** [comment]
Please see issue ( https://github.com/conda-forge/conda-forge.github.io/issues/426 ) and in particular please read this [comment]( https://github.com/conda-forge/conda-forge.github.io/issues/426#issuecomment-321897876 ).

**Comment by inducer** [comment]
OK, looks like the best course of action here is to just leave this be
until the ecosystem recovers.

**Comment by asmeurer** [comment]
Agreed.

**Comment by inducer** [comment]
Thanks @jakirkham for the heads-up!

**Comment by isuruf** [comment]
Token was fixed for all feedstocks. See https://github.com/conda-forge/conda-forge.github.io/issues/426

You'll have to restart the builds.

**Comment by inducer** [comment]
Thanks @isuruf. Bumped the builds.

**Comment by asmeurer** [comment]
Didn't work? I just pushed a bump commit.

**Comment by inducer** [comment]
No, did work. I just initially bumped the wrong builds--that's where the error msg came from.
